spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/bishari_ocean_view_resort
server.port=8080

# Mailtrap Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3f16df948dbab5
spring.mail.password=f5826566593bf6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
